#include "ToolDefinitions.h"

#include <map>

namespace {

const std::map<std::string, std::string>& tool_definitions() {
    static const std::map<std::string, std::string> definitions = {
        {"read_file", R"JSON({"name":"read_file","description":"Read a file from disk","inputSchema":{"type":"object","properties":{"path":{"type":"string","description":"File path to read from disk"}},"required":["path"]}})JSON"},
        {"write_file", R"JSON({"name":"write_file","description":"Create or focus a file in the live editor, type the provided content into the tab, then wait for the human user to Save or Revert before returning. If the target file already exists, a .bak-XX backup copy is created first for safety. Large inputs may be inserted instantly to avoid client timeouts, but still require Save or Revert.","inputSchema":{"type":"object","properties":{"path":{"type":"string","description":"File path to create/open in the editor"},"content":{"type":"string","description":"Full file contents to type into the editor tab. Preserve exact Unicode and newlines."}},"required":["path","content"]}})JSON"},
        {"edit_file", R"JSON({"name":"edit_file","description":"Open or focus a file in the live editor, find the exact oldtext, replace it by typing newtext in place, then wait for the human user to Save or Revert before returning. A .bak-XX backup copy of the original file is created first for safety. Large inputs may be inserted instantly to avoid client timeouts, but still require Save or Revert.","inputSchema":{"type":"object","properties":{"path":{"type":"string","description":"File path to edit in the editor"},"oldtext":{"type":"string","description":"Exact existing text to locate and replace. Required even when short."},"newtext":{"type":"string","description":"Replacement text to type into the editor in place of oldtext. Preserve exact Unicode and newlines."}},"required":["path","oldtext","newtext"]}})JSON"},
        {"create_directory", R"JSON({"name":"create_directory","description":"Create a directory path, including parents, and return the resolved path.","inputSchema":{"type":"object","properties":{"path":{"type":"string","description":"Directory path to create"}},"required":["path"]}})JSON"},
        {"list_directory", R"JSON({"name":"list_directory","description":"List files and directories directly inside a path.","inputSchema":{"type":"object","properties":{"path":{"type":"string","description":"Directory path to list"}},"required":["path"]}})JSON"},
        {"list_directory_with_sizes", R"JSON({"name":"list_directory_with_sizes","description":"List a directory with file sizes and modification times.","inputSchema":{"type":"object","properties":{"path":{"type":"string","description":"Directory path to list"},"sortBy":{"type":"string","enum":["name","size"],"description":"Sort entries by name or size"}},"required":["path"]}})JSON"},
        {"directory_tree", R"JSON({"name":"directory_tree","description":"Recursively build a tree of files and directories.","inputSchema":{"type":"object","properties":{"path":{"type":"string","description":"Root directory to inspect"}},"required":["path"]}})JSON"},
        {"move_file", R"JSON({"name":"move_file","description":"Move or rename a file or directory.","inputSchema":{"type":"object","properties":{"source":{"type":"string","description":"Source path"},"destination":{"type":"string","description":"Destination path"}},"required":["source","destination"]}})JSON"},
        {"search_files", R"JSON({"name":"search_files","description":"Recursively search for matching files and directories by name.","inputSchema":{"type":"object","properties":{"path":{"type":"string","description":"Root directory to search"},"pattern":{"type":"string","description":"Case-insensitive name fragment to search for"},"excludePatterns":{"type":"array","items":{"type":"string"},"description":"Optional exclude patterns"}},"required":["path","pattern"]}})JSON"},
        {"get_file_info", R"JSON({"name":"get_file_info","description":"Return metadata for a file or directory.","inputSchema":{"type":"object","properties":{"path":{"type":"string","description":"Path to inspect"}},"required":["path"]}})JSON"},
        {"glob_files", R"JSON({"name":"glob_files","description":"Find files matching a POSIX-like glob pattern. Supports * (any chars in segment), ? (single char), and ** (recursive directory traversal). Returns relative paths sorted alphabetically. Limited to 500 results.","inputSchema":{"type":"object","properties":{"pattern":{"type":"string","description":"Glob pattern, e.g. '**/*.cpp', '*.h', 'src/**/*.txt'"},"path":{"type":"string","description":"Root directory to search from. Defaults to current directory."}},"required":["pattern"]}})JSON"},
        {"grep_files", R"JSON({"name":"grep_files","description":"Search file contents using a regex pattern across all files in a directory tree. Skips binary files automatically. Returns file path, line number, and matching line text for each hit. Limited to 100 results by default (max 10000).","inputSchema":{"type":"object","properties":{"pattern":{"type":"string","description":"Regular expression pattern to search for"},"path":{"type":"string","description":"Root directory to search. Defaults to current directory."},"include":{"type":"string","description":"Optional filename glob filter, e.g. '*.cpp' to only search C++ files"},"max_results":{"type":"number","description":"Maximum number of matches to return. Default 100, max 10000."}},"required":["pattern"]}})JSON"},
        {"symbols", R"JSON({"name":"symbols","description":"Code navigation. Commands: get (list symbols in file), def (find definition), ref (find references), signature, doc, type, inherit, hierarchy.","inputSchema":{"type":"object","properties":{"command":{"type":"string","description":"Subcommand: get, def, ref, signature, doc, type, inherit, hierarchy"},"path":{"type":"string","description":"File path to analyze"},"symbol":{"type":"string","description":"Symbol name to search for (required for def, ref)"}},"required":["command"]}})JSON"},
        {"git", R"JSON({"name":"git","description":"Version control queries. Commands: diff, status, log, blame, branch, commit_files.","inputSchema":{"type":"object","properties":{"command":{"type":"string","description":"Subcommand: diff, status, log, blame, branch, commit_files"},"path":{"type":"string","description":"Path inside a git repo. Defaults to current directory."},"staged":{"type":"string","description":"For diff: 'true' to show staged changes"},"file":{"type":"string","description":"For diff/blame: specific file to query"},"max":{"type":"number","description":"For log: max commits to return. Default 20."},"hash":{"type":"string","description":"For commit_files: commit hash. Defaults to HEAD."}},"required":["command"]}})JSON"},
        {"project", R"JSON({"name":"project","description":"File and workspace structure. Commands: list, info, tree, root, config, diff, recent, workspace.","inputSchema":{"type":"object","properties":{"command":{"type":"string","description":"Subcommand: list, info, tree, root, config, diff, recent, workspace"},"path":{"type":"string","description":"Directory or file path to query"},"file_a":{"type":"string","description":"For diff: first file"},"file_b":{"type":"string","description":"For diff: second file"},"max_depth":{"type":"number","description":"For tree: max recursion depth. Default 4."}},"required":["command"]}})JSON"},
        {"build", R"JSON({"name":"build","description":"Build, test, and lint workflows. Commands: diagnostics, build, log, test, run, lint, format.","inputSchema":{"type":"object","properties":{"command":{"type":"string","description":"Subcommand: diagnostics, build, log, test, run, lint, format"},"build_dir":{"type":"string","description":"Build directory. Defaults to current directory."},"target":{"type":"string","description":"For build: cmake target name"},"command_line":{"type":"string","description":"For run: shell command to execute"},"timeout":{"type":"number","description":"For run: timeout in seconds. Default 30."}},"required":["command"]}})JSON"},
        {"editor", R"JSON({"name":"editor","description":"Live editor state queries. Commands: state, tabs, cursor, selection, outline, recent_symbols, hotspots, activity.","inputSchema":{"type":"object","properties":{"command":{"type":"string","description":"Subcommand: state, tabs, cursor, selection, outline, recent_symbols, hotspots, activity"}},"required":["command"]}})JSON"},
        {"analyze", R"JSON({"name":"analyze","description":"Code analysis. Commands: complexity, dead_code, unused, cycles, long, duplicate, naming, ast, preprocessor, include_graph.","inputSchema":{"type":"object","properties":{"command":{"type":"string","description":"Subcommand: complexity, dead_code, unused, cycles, long, duplicate, naming, ast, preprocessor, include_graph"},"path":{"type":"string","description":"File or directory to analyze"},"threshold":{"type":"number","description":"For long: minimum line count to flag. Default 50."}},"required":["command"]}})JSON"},
        {"refactor", R"JSON({"name":"refactor","description":"Code transformation previews. Commands: extract, variable, inline, signature, move_file, split, merge.","inputSchema":{"type":"object","properties":{"command":{"type":"string","description":"Subcommand: extract, variable, inline, signature, move_file, split, merge"}},"required":["command"]}})JSON"},
        {"bash", R"JSON({"name":"bash","description":"Run shell commands through WinuxCmd. Supported subcommands: execute (default if omitted), set_cwd, get_cwd, run_background, kill_background, list_background. For common case, send {\"cmd\":\"...\"} and it will execute command even if \"command\" is missing. Use {\"command\":\"set_cwd\",\"path\":\"...\"} to change working directory, or {\"command\":\"get_cwd\"} to read it back. Background processes support && and ; command chaining.","inputSchema":{"type":"object","properties":{"command":{"type":"string","description":"Optional subcommand. Omit for normal command execution. Valid values: execute, set_cwd, get_cwd, run_background, kill_background, list_background."},"cmd":{"type":"string","description":"Shell command to execute. For run_background, this is command to run in background. If present without command, execution is assumed."},"name":{"type":"string","description":"Unique name for background process (required for run_background and kill_background)"},"cwd":{"type":"string","description":"Working directory for execute. Optional; defaults to current bash working directory."},"path":{"type":"string","description":"Path used by set_cwd."},"timeout":{"type":"number","description":"Timeout in milliseconds for execute (default: 30000)"}},"required":[]}})JSON"},
        {"terminal", R"JSON({"name":"terminal","description":"Control the built-in terminal window. Use show to open or focus the terminal, hide to dismiss it. This tool is UI-only; it does not execute shell commands.","inputSchema":{"type":"object","properties":{"command":{"type":"string","description":"Required terminal action. Valid values: show, hide."}},"required":["command"]}})JSON"},
        {"sequentialthinking", R"JSON({"name":"sequentialthinking","description":"Structured multi-step reasoning with optional revisions and branches.","inputSchema":{"type":"object","properties":{"thought":{"type":"string","description":"Current thought"},"nextThoughtNeeded":{"type":"boolean"},"thoughtNumber":{"type":"integer","minimum":1},"totalThoughts":{"type":"integer","minimum":1},"isRevision":{"type":"boolean"},"revisesThought":{"type":"integer","minimum":1},"branchFromThought":{"type":"integer","minimum":1},"branchId":{"type":"string"},"needsMoreThoughts":{"type":"boolean"}},"required":["thought","nextThoughtNeeded","thoughtNumber","totalThoughts"]}})JSON"},
        {"create_entities", R"JSON({"name":"create_entities","description":"Create multiple new entities in the knowledge graph","inputSchema":{"type":"object","properties":{"entities":{"type":"array","items":{"type":"object","properties":{"name":{"type":"string","description":"The name of the entity"},"entityType":{"type":"string","description":"The type of the entity"},"observations":{"type":"array","items":{"type":"string"},"description":"An array of observation contents associated with the entity"}},"required":["name","entityType","observations"]}}},"required":["entities"]}})JSON"},
        {"create_relations", R"JSON({"name":"create_relations","description":"Create multiple new relations between entities in the knowledge graph. Relations should be in active voice","inputSchema":{"type":"object","properties":{"relations":{"type":"array","items":{"type":"object","properties":{"from":{"type":"string","description":"The name of the entity where the relation starts"},"to":{"type":"string","description":"The name of the entity where the relation ends"},"relationType":{"type":"string","description":"The type of the relation"}},"required":["from","to","relationType"]}}},"required":["relations"]}})JSON"},
        {"add_observations", R"JSON({"name":"add_observations","description":"Add new observations to existing entities in the knowledge graph","inputSchema":{"type":"object","properties":{"observations":{"type":"array","items":{"type":"object","properties":{"entityName":{"type":"string","description":"The name of the entity to add the observations to"},"contents":{"type":"array","items":{"type":"string"},"description":"An array of observation contents to add"}},"required":["entityName","contents"]}}},"required":["observations"]}})JSON"},
        {"delete_entities", R"JSON({"name":"delete_entities","description":"Delete multiple entities and their associated relations from the knowledge graph","inputSchema":{"type":"object","properties":{"entityNames":{"type":"array","items":{"type":"string"},"description":"An array of entity names to delete"}},"required":["entityNames"]}})JSON"},
        {"delete_observations", R"JSON({"name":"delete_observations","description":"Delete specific observations from entities in the knowledge graph","inputSchema":{"type":"object","properties":{"deletions":{"type":"array","items":{"type":"object","properties":{"entityName":{"type":"string","description":"The name of the entity containing the observations"},"observations":{"type":"array","items":{"type":"string"},"description":"An array of observations to delete"}},"required":["entityName","observations"]}}},"required":["deletions"]}})JSON"},
        {"delete_relations", R"JSON({"name":"delete_relations","description":"Delete multiple relations from the knowledge graph","inputSchema":{"type":"object","properties":{"relations":{"type":"array","items":{"type":"object","properties":{"from":{"type":"string","description":"The name of the entity where the relation starts"},"to":{"type":"string","description":"The name of the entity where the relation ends"},"relationType":{"type":"string","description":"The type of the relation"}},"required":["from","to","relationType"]},"description":"An array of relations to delete"}},"required":["relations"]}})JSON"},
        {"read_graph", R"JSON({"name":"read_graph","description":"Read the entire knowledge graph","inputSchema":{"type":"object","properties":{}}})JSON"},
        {"search_nodes", R"JSON({"name":"search_nodes","description":"Search for nodes in the knowledge graph based on a query","inputSchema":{"type":"object","properties":{"query":{"type":"string","description":"The search query to match against entity names, types, and observation content"}},"required":["query"]}})JSON"},
        {"open_nodes", R"JSON({"name":"open_nodes","description":"Open specific nodes in the knowledge graph by their names","inputSchema":{"type":"object","properties":{"names":{"type":"array","items":{"type":"string"},"description":"An array of entity names to retrieve"}},"required":["names"]}})JSON"}
    };
    return definitions;
}

const std::vector<std::string>& tool_names() {
    static const std::vector<std::string> names = {
        "read_file", "write_file", "edit_file", "create_directory", "list_directory",
        "list_directory_with_sizes", "directory_tree", "move_file", "search_files", "get_file_info",
        "glob_files", "grep_files", "symbols", "git", "project", "build", "editor",
        "analyze", "refactor", "bash", "terminal", "sequentialthinking", "create_entities",
        "create_relations", "add_observations", "delete_entities", "delete_observations",
        "delete_relations", "read_graph", "search_nodes", "open_nodes"
    };
    return names;
}

} // namespace

namespace ToolDefinitions {

const std::vector<std::string>& AllToolNames() {
    return tool_names();
}

std::string DefinitionJson(const std::string& tool_name) {
    const auto& definitions = tool_definitions();
    auto it = definitions.find(tool_name);
    if (it == definitions.end()) {
        return "";
    }
    return it->second;
}

} // namespace ToolDefinitions
